name: flutter_mix
description: UI experiments with Flutter. What else?

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/calendar.png
    - images/dummy1.jpg
    - images/dummy2.jpg
    - images/dummy3.jpg
